// ------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (c) CareSource, 2019. All rights reserved.
// 
//   WC.Services.OnBase
//   BaseResponse.cs
// </copyright>
// ------------------------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace

namespace WC.Services.OnBase.Dotnet8.Models
{
	using System;
	using Newtonsoft.Json;

	public class BaseResponse<TResult>
	{
		[JsonConstructor]
		public BaseResponse(
			string title,
			int status,
			TResult result)
		{
			Title = title;
			Status = status;
			Result = result;
		}


		public BaseResponse(
			string title,
			int status)
			: this(
				title,
				status,
				default)
		{ }

		/// <summary>
		///    A short, human-readable summary of the problem type.It SHOULD NOT change from
		///    occurrence to occurrence of the problem, except for purposes of
		///    localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "title")]
		public string Title { get; set; }

		/// <summary>
		///    The HTTP status code([RFC7231], Section 6) generated by the origin server for this
		///    occurrence of the problem.
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "status")]
		public int? Status { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Response Data
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "result")]
		public TResult Result { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Trace Identifier
		/// </summary>
		//[JsonProperty(PropertyName = "correlationGuid")]
		//public Guid CorrelationGuid { get; set; }
	}
}