// ------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (c) CareSource, 2021. All rights reserved.
// 
//   ImportProcessor
//   DocTypeNameResponse.cs
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace ImportProcessor.Models.v1
{
	using System;
	using System.Collections.Generic;
	using Newtonsoft.Json;

	public class DocTypeNameResponse : DocBaseResponse<DocumentType>
	{
		[JsonConstructor]
		public DocTypeNameResponse(
			string title,
			int status,
			Guid correlationGuid,
			DocumentType result)
			: base(
				title,
				status,
				correlationGuid,
				result)
		{ }

		public DocTypeNameResponse(
			string title,
			int status,
			Guid correlationGuid)
			: base(
				title,
				status,
				correlationGuid)
		{ }
	}

	public abstract class BaseModel
	{
		public long Id { get; set; }

		public string Name { get; set; }
	}

	public class DocumentType : BaseModel
	{
		public IEnumerable<Keyword> Keywords { get; set; }
	}

	public class DocBaseResponse<TResult>
	{
		[JsonConstructor]
		public DocBaseResponse(
			string title,
			int status,
			Guid correlationGuid,
			TResult result)
		{
			Title = title;
			Status = status;
			CorrelationGuid = correlationGuid;
			Result = result;
		}

		public DocBaseResponse(
			string title,
			int status,
			Guid correlationGuid)
			: this(
				title,
				status,
				correlationGuid,
				default)
		{ }

		/// <summary>
		///    A short, human-readable summary of the problem type.It SHOULD NOT change from
		///    occurrence to occurrence of the problem, except for purposes of
		///    localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "title")]
		public string Title { get; set; }

		/// <summary>
		///    The HTTP status code([RFC7231], Section 6) generated by the origin server for this
		///    occurrence of the problem.
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "status")]
		public int? Status { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Response Data
		/// </summary>
		[JsonProperty(
			NullValueHandling = NullValueHandling.Ignore,
			PropertyName = "result")]
		public TResult Result { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Trace Identifier
		/// </summary>
		[JsonProperty(PropertyName = "correlationGuid")]
		public Guid CorrelationGuid { get; set; }
	}
}