//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareSource.WC.Services.Eligibility.ConnectedServices.Facets.Eligibility.Get
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", ConfigurationName="Facets.Eligibility.Get.WebSvcProcessEligRangeSoap")]
    public interface WebSvcProcessEligRangeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange/ProcessEligRange_MemberKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecordBase))]
        System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKeyResponse> ProcessEligRange_MemberKeyAsync(Facets.Eligibility.Get.ProcessEligRange_MemberKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange/ProcessEligRange_MemberKey_" +
            "Cat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RecordBase))]
        System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatResponse> ProcessEligRange_MemberKey_CatAsync(Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public partial class FxiIslHeader
    {
        
        private PartnerType partnerField;
        
        private HdrCollection dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PartnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public HdrCollection Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public partial class PartnerType
    {
        
        private PartnerNameType partnerNameField;
        
        private string partnerIdField;
        
        private string partnerTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PartnerNameType PartnerName
        {
            get
            {
                return this.partnerNameField;
            }
            set
            {
                this.partnerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerTime
        {
            get
            {
                return this.partnerTimeField;
            }
            set
            {
                this.partnerTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public enum PartnerNameType
    {
        
        /// <remarks/>
        Facets,
        
        /// <remarks/>
        HealthWeb,
        
        /// <remarks/>
        NetworX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public partial class HdrColumn
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public partial class HdrCollection
    {
        
        private HdrColumn[] columnField;
        
        private HdrCollection[] subCollectionField;
        
        private CollectionTypeList typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Column", IsNullable=true, Order=0)]
        public HdrColumn[] Column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubCollection", IsNullable=true, Order=1)]
        public HdrCollection[] SubCollection
        {
            get
            {
                return this.subCollectionField;
            }
            set
            {
                this.subCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CollectionTypeList type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl")]
    public enum CollectionTypeList
    {
        
        /// <remarks/>
        SoapHeader,
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        Row,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessEligRangeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REC_ERR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REC_RESP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(REC_MEPE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Config))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class RecordBase
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessEligRangeResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class Response : RecordBase
    {
        
        private int appReturnCodeField;
        
        private REC_ERR[] appErrorsField;
        
        private REC_RESP[] rESP_COLLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AppReturnCode
        {
            get
            {
                return this.appReturnCodeField;
            }
            set
            {
                this.appReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public REC_ERR[] AppErrors
        {
            get
            {
                return this.appErrorsField;
            }
            set
            {
                this.appErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public REC_RESP[] RESP_COLL
        {
            get
            {
                return this.rESP_COLLField;
            }
            set
            {
                this.rESP_COLLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class REC_ERR : RecordBase
    {
        
        private string eRR_IDField;
        
        private string eRR_CODEField;
        
        private string eRR_CONTEXTField;
        
        private string eRR_MSG_USERField;
        
        private string eRR_MSG_SYSField;
        
        private string eRR_MSG_PROGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ERR_ID
        {
            get
            {
                return this.eRR_IDField;
            }
            set
            {
                this.eRR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ERR_CODE
        {
            get
            {
                return this.eRR_CODEField;
            }
            set
            {
                this.eRR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ERR_CONTEXT
        {
            get
            {
                return this.eRR_CONTEXTField;
            }
            set
            {
                this.eRR_CONTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ERR_MSG_USER
        {
            get
            {
                return this.eRR_MSG_USERField;
            }
            set
            {
                this.eRR_MSG_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ERR_MSG_SYS
        {
            get
            {
                return this.eRR_MSG_SYSField;
            }
            set
            {
                this.eRR_MSG_SYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ERR_MSG_PROG
        {
            get
            {
                return this.eRR_MSG_PROGField;
            }
            set
            {
                this.eRR_MSG_PROGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class REC_RESP : RecordBase
    {
        
        private string pITM_TICKET_NOField;
        
        private int pITM_STSField;
        
        private string rESP_SERVICEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PITM_TICKET_NO
        {
            get
            {
                return this.pITM_TICKET_NOField;
            }
            set
            {
                this.pITM_TICKET_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PITM_STS
        {
            get
            {
                return this.pITM_STSField;
            }
            set
            {
                this.pITM_STSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RESP_SERVICE
        {
            get
            {
                return this.rESP_SERVICEField;
            }
            set
            {
                this.rESP_SERVICEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class ProcessEligRangeResponse : Response
    {
        
        private REC_MEPE[] mEPE_COLLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public REC_MEPE[] MEPE_COLL
        {
            get
            {
                return this.mEPE_COLLField;
            }
            set
            {
                this.mEPE_COLLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class REC_MEPE : RecordBase
    {
        
        private System.Nullable<long> mEME_CKField;
        
        private string cSPD_CATField;
        
        private string cSPD_CAT_DESCField;
        
        private System.Nullable<System.DateTime> mEPE_EFF_DTField;
        
        private System.Nullable<System.DateTime> mEPE_TERM_DTField;
        
        private string cSCS_IDField;
        
        private string cSCS_DESCField;
        
        private string sGSG_CKField;
        
        private string sGSG_IDField;
        
        private string sGSG_NAMEField;
        
        private string gRGR_CKField;
        
        private string gRGR_IDField;
        
        private string gRGR_NAMEField;
        
        private string cSPI_IDField;
        
        private string pLDS_DESCField;
        
        private string pDPD_IDField;
        
        private string pDDS_DESCField;
        
        private string mEPE_ELIG_INDField;
        
        private string mEPE_ELIG_IND_DESCField;
        
        private string eXCD_IDField;
        
        private string eXCD_ID_DESCField;
        
        private string mEPE_MCTR_RSNField;
        
        private string mEPE_MCTR_RSN_DESCField;
        
        private string mEPE_SYS_INEL_CDField;
        
        private string mEPE_SYS_INEL_CD_DESCField;
        
        private string mEPE_FIField;
        
        private string mEPE_MCTR_FI_DESCField;
        
        private string mEPE_PRCS_STSField;
        
        private string mEPE_PRCS_STS_DESCField;
        
        private string mEPE_ELIG_OVR_INDField;
        
        private string mEPE_ELIG_OVR_IND_DESCField;
        
        private string mEPE_HAS_MEDX_INDField;
        
        private string mEPE_HAS_MEDX_IND_DESCField;
        
        private string mEPE_HAS_WARN_CDField;
        
        private string mEPE_HAS_WARN_CD_DESCField;
        
        private string mEPE_SOURCEField;
        
        private string mEPE_SOURCE_DESCField;
        
        private System.Nullable<System.DateTime> mEPE_PLAN_ENTRY_DTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> MEME_CK
        {
            get
            {
                return this.mEME_CKField;
            }
            set
            {
                this.mEME_CKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CSPD_CAT
        {
            get
            {
                return this.cSPD_CATField;
            }
            set
            {
                this.cSPD_CATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CSPD_CAT_DESC
        {
            get
            {
                return this.cSPD_CAT_DESCField;
            }
            set
            {
                this.cSPD_CAT_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> MEPE_EFF_DT
        {
            get
            {
                return this.mEPE_EFF_DTField;
            }
            set
            {
                this.mEPE_EFF_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> MEPE_TERM_DT
        {
            get
            {
                return this.mEPE_TERM_DTField;
            }
            set
            {
                this.mEPE_TERM_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CSCS_ID
        {
            get
            {
                return this.cSCS_IDField;
            }
            set
            {
                this.cSCS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CSCS_DESC
        {
            get
            {
                return this.cSCS_DESCField;
            }
            set
            {
                this.cSCS_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SGSG_CK
        {
            get
            {
                return this.sGSG_CKField;
            }
            set
            {
                this.sGSG_CKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SGSG_ID
        {
            get
            {
                return this.sGSG_IDField;
            }
            set
            {
                this.sGSG_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SGSG_NAME
        {
            get
            {
                return this.sGSG_NAMEField;
            }
            set
            {
                this.sGSG_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GRGR_CK
        {
            get
            {
                return this.gRGR_CKField;
            }
            set
            {
                this.gRGR_CKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string GRGR_ID
        {
            get
            {
                return this.gRGR_IDField;
            }
            set
            {
                this.gRGR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string GRGR_NAME
        {
            get
            {
                return this.gRGR_NAMEField;
            }
            set
            {
                this.gRGR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CSPI_ID
        {
            get
            {
                return this.cSPI_IDField;
            }
            set
            {
                this.cSPI_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PLDS_DESC
        {
            get
            {
                return this.pLDS_DESCField;
            }
            set
            {
                this.pLDS_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PDPD_ID
        {
            get
            {
                return this.pDPD_IDField;
            }
            set
            {
                this.pDPD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PDDS_DESC
        {
            get
            {
                return this.pDDS_DESCField;
            }
            set
            {
                this.pDDS_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MEPE_ELIG_IND
        {
            get
            {
                return this.mEPE_ELIG_INDField;
            }
            set
            {
                this.mEPE_ELIG_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string MEPE_ELIG_IND_DESC
        {
            get
            {
                return this.mEPE_ELIG_IND_DESCField;
            }
            set
            {
                this.mEPE_ELIG_IND_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string EXCD_ID
        {
            get
            {
                return this.eXCD_IDField;
            }
            set
            {
                this.eXCD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string EXCD_ID_DESC
        {
            get
            {
                return this.eXCD_ID_DESCField;
            }
            set
            {
                this.eXCD_ID_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MEPE_MCTR_RSN
        {
            get
            {
                return this.mEPE_MCTR_RSNField;
            }
            set
            {
                this.mEPE_MCTR_RSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string MEPE_MCTR_RSN_DESC
        {
            get
            {
                return this.mEPE_MCTR_RSN_DESCField;
            }
            set
            {
                this.mEPE_MCTR_RSN_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string MEPE_SYS_INEL_CD
        {
            get
            {
                return this.mEPE_SYS_INEL_CDField;
            }
            set
            {
                this.mEPE_SYS_INEL_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string MEPE_SYS_INEL_CD_DESC
        {
            get
            {
                return this.mEPE_SYS_INEL_CD_DESCField;
            }
            set
            {
                this.mEPE_SYS_INEL_CD_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string MEPE_FI
        {
            get
            {
                return this.mEPE_FIField;
            }
            set
            {
                this.mEPE_FIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string MEPE_MCTR_FI_DESC
        {
            get
            {
                return this.mEPE_MCTR_FI_DESCField;
            }
            set
            {
                this.mEPE_MCTR_FI_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string MEPE_PRCS_STS
        {
            get
            {
                return this.mEPE_PRCS_STSField;
            }
            set
            {
                this.mEPE_PRCS_STSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string MEPE_PRCS_STS_DESC
        {
            get
            {
                return this.mEPE_PRCS_STS_DESCField;
            }
            set
            {
                this.mEPE_PRCS_STS_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string MEPE_ELIG_OVR_IND
        {
            get
            {
                return this.mEPE_ELIG_OVR_INDField;
            }
            set
            {
                this.mEPE_ELIG_OVR_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string MEPE_ELIG_OVR_IND_DESC
        {
            get
            {
                return this.mEPE_ELIG_OVR_IND_DESCField;
            }
            set
            {
                this.mEPE_ELIG_OVR_IND_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string MEPE_HAS_MEDX_IND
        {
            get
            {
                return this.mEPE_HAS_MEDX_INDField;
            }
            set
            {
                this.mEPE_HAS_MEDX_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string MEPE_HAS_MEDX_IND_DESC
        {
            get
            {
                return this.mEPE_HAS_MEDX_IND_DESCField;
            }
            set
            {
                this.mEPE_HAS_MEDX_IND_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string MEPE_HAS_WARN_CD
        {
            get
            {
                return this.mEPE_HAS_WARN_CDField;
            }
            set
            {
                this.mEPE_HAS_WARN_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string MEPE_HAS_WARN_CD_DESC
        {
            get
            {
                return this.mEPE_HAS_WARN_CD_DESCField;
            }
            set
            {
                this.mEPE_HAS_WARN_CD_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string MEPE_SOURCE
        {
            get
            {
                return this.mEPE_SOURCEField;
            }
            set
            {
                this.mEPE_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string MEPE_SOURCE_DESC
        {
            get
            {
                return this.mEPE_SOURCE_DESCField;
            }
            set
            {
                this.mEPE_SOURCE_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<System.DateTime> MEPE_PLAN_ENTRY_DT
        {
            get
            {
                return this.mEPE_PLAN_ENTRY_DTField;
            }
            set
            {
                this.mEPE_PLAN_ENTRY_DTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange")]
    public partial class Config : RecordBase
    {
        
        private string facetsIdentityField;
        
        private string callingSystemNameField;
        
        private string callingSystemUserIdField;
        
        private string callingSystemUserNameField;
        
        private string callingSystemTransactionIdField;
        
        private string[] requestedColumnsField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FacetsIdentity
        {
            get
            {
                return this.facetsIdentityField;
            }
            set
            {
                this.facetsIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CallingSystemName
        {
            get
            {
                return this.callingSystemNameField;
            }
            set
            {
                this.callingSystemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CallingSystemUserId
        {
            get
            {
                return this.callingSystemUserIdField;
            }
            set
            {
                this.callingSystemUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CallingSystemUserName
        {
            get
            {
                return this.callingSystemUserNameField;
            }
            set
            {
                this.callingSystemUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CallingSystemTransactionId
        {
            get
            {
                return this.callingSystemTransactionIdField;
            }
            set
            {
                this.callingSystemTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] RequestedColumns
        {
            get
            {
                return this.requestedColumnsField;
            }
            set
            {
                this.requestedColumnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEligRange_MemberKey", WrapperNamespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", IsWrapped=true)]
    public partial class ProcessEligRange_MemberKeyRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://trizetto.com/fxi/isl")]
        public Facets.Eligibility.Get.FxiIslHeader FxiIslHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=0)]
        public Facets.Eligibility.Get.Config pConfig;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> pMEME_CK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pFROM_DT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pTO_DT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=4)]
        public string pELIGIBILITY_IND;
        
        public ProcessEligRange_MemberKeyRequest()
        {
        }
        
        public ProcessEligRange_MemberKeyRequest(Facets.Eligibility.Get.FxiIslHeader FxiIslHeader, Facets.Eligibility.Get.Config pConfig, System.Nullable<long> pMEME_CK, System.Nullable<System.DateTime> pFROM_DT, System.Nullable<System.DateTime> pTO_DT, string pELIGIBILITY_IND)
        {
            this.FxiIslHeader = FxiIslHeader;
            this.pConfig = pConfig;
            this.pMEME_CK = pMEME_CK;
            this.pFROM_DT = pFROM_DT;
            this.pTO_DT = pTO_DT;
            this.pELIGIBILITY_IND = pELIGIBILITY_IND;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEligRange_MemberKeyResponse", WrapperNamespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", IsWrapped=true)]
    public partial class ProcessEligRange_MemberKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=0)]
        public Facets.Eligibility.Get.ProcessEligRangeResponse ProcessEligRange_MemberKeyResult;
        
        public ProcessEligRange_MemberKeyResponse()
        {
        }
        
        public ProcessEligRange_MemberKeyResponse(Facets.Eligibility.Get.ProcessEligRangeResponse ProcessEligRange_MemberKeyResult)
        {
            this.ProcessEligRange_MemberKeyResult = ProcessEligRange_MemberKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEligRange_MemberKey_Cat", WrapperNamespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", IsWrapped=true)]
    public partial class ProcessEligRange_MemberKey_CatRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://trizetto.com/fxi/isl")]
        public Facets.Eligibility.Get.FxiIslHeader FxiIslHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=0)]
        public Facets.Eligibility.Get.Config pConfig;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> pMEME_CK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pFROM_DT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pTO_DT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=4)]
        public string pCSPD_CAT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=5)]
        public string pELIGIBILITY_IND;
        
        public ProcessEligRange_MemberKey_CatRequest()
        {
        }
        
        public ProcessEligRange_MemberKey_CatRequest(Facets.Eligibility.Get.FxiIslHeader FxiIslHeader, Facets.Eligibility.Get.Config pConfig, System.Nullable<long> pMEME_CK, System.Nullable<System.DateTime> pFROM_DT, System.Nullable<System.DateTime> pTO_DT, string pCSPD_CAT, string pELIGIBILITY_IND)
        {
            this.FxiIslHeader = FxiIslHeader;
            this.pConfig = pConfig;
            this.pMEME_CK = pMEME_CK;
            this.pFROM_DT = pFROM_DT;
            this.pTO_DT = pTO_DT;
            this.pCSPD_CAT = pCSPD_CAT;
            this.pELIGIBILITY_IND = pELIGIBILITY_IND;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEligRange_MemberKey_CatResponse", WrapperNamespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", IsWrapped=true)]
    public partial class ProcessEligRange_MemberKey_CatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trizetto.com/fxi/isl/FaWsvcInpProcessEligRange", Order=0)]
        public Facets.Eligibility.Get.ProcessEligRangeResponse ProcessEligRange_MemberKey_CatResult;
        
        public ProcessEligRange_MemberKey_CatResponse()
        {
        }
        
        public ProcessEligRange_MemberKey_CatResponse(Facets.Eligibility.Get.ProcessEligRangeResponse ProcessEligRange_MemberKey_CatResult)
        {
            this.ProcessEligRange_MemberKey_CatResult = ProcessEligRange_MemberKey_CatResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface WebSvcProcessEligRangeSoapChannel : Facets.Eligibility.Get.WebSvcProcessEligRangeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class WebSvcProcessEligRangeSoapClient : System.ServiceModel.ClientBase<Facets.Eligibility.Get.WebSvcProcessEligRangeSoap>, Facets.Eligibility.Get.WebSvcProcessEligRangeSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebSvcProcessEligRangeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebSvcProcessEligRangeSoapClient.GetBindingForEndpoint(endpointConfiguration), WebSvcProcessEligRangeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSvcProcessEligRangeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebSvcProcessEligRangeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSvcProcessEligRangeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebSvcProcessEligRangeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSvcProcessEligRangeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKeyResponse> Facets.Eligibility.Get.WebSvcProcessEligRangeSoap.ProcessEligRange_MemberKeyAsync(Facets.Eligibility.Get.ProcessEligRange_MemberKeyRequest request)
        {
            return base.Channel.ProcessEligRange_MemberKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKeyResponse> ProcessEligRange_MemberKeyAsync(Facets.Eligibility.Get.FxiIslHeader FxiIslHeader, Facets.Eligibility.Get.Config pConfig, System.Nullable<long> pMEME_CK, System.Nullable<System.DateTime> pFROM_DT, System.Nullable<System.DateTime> pTO_DT, string pELIGIBILITY_IND)
        {
            Facets.Eligibility.Get.ProcessEligRange_MemberKeyRequest inValue = new Facets.Eligibility.Get.ProcessEligRange_MemberKeyRequest();
            inValue.FxiIslHeader = FxiIslHeader;
            inValue.pConfig = pConfig;
            inValue.pMEME_CK = pMEME_CK;
            inValue.pFROM_DT = pFROM_DT;
            inValue.pTO_DT = pTO_DT;
            inValue.pELIGIBILITY_IND = pELIGIBILITY_IND;
            return ((Facets.Eligibility.Get.WebSvcProcessEligRangeSoap)(this)).ProcessEligRange_MemberKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatResponse> Facets.Eligibility.Get.WebSvcProcessEligRangeSoap.ProcessEligRange_MemberKey_CatAsync(Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatRequest request)
        {
            return base.Channel.ProcessEligRange_MemberKey_CatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatResponse> ProcessEligRange_MemberKey_CatAsync(Facets.Eligibility.Get.FxiIslHeader FxiIslHeader, Facets.Eligibility.Get.Config pConfig, System.Nullable<long> pMEME_CK, System.Nullable<System.DateTime> pFROM_DT, System.Nullable<System.DateTime> pTO_DT, string pCSPD_CAT, string pELIGIBILITY_IND)
        {
            Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatRequest inValue = new Facets.Eligibility.Get.ProcessEligRange_MemberKey_CatRequest();
            inValue.FxiIslHeader = FxiIslHeader;
            inValue.pConfig = pConfig;
            inValue.pMEME_CK = pMEME_CK;
            inValue.pFROM_DT = pFROM_DT;
            inValue.pTO_DT = pTO_DT;
            inValue.pCSPD_CAT = pCSPD_CAT;
            inValue.pELIGIBILITY_IND = pELIGIBILITY_IND;
            return ((Facets.Eligibility.Get.WebSvcProcessEligRangeSoap)(this)).ProcessEligRange_MemberKey_CatAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebSvcProcessEligRangeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebSvcProcessEligRangeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebSvcProcessEligRangeSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dayintfacfxi01/FacetsWebServiceLibrary/FaWsvcInpProcessEligRange.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebSvcProcessEligRangeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dayintfacfxi01/FacetsWebServiceLibrary/FaWsvcInpProcessEligRange.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebSvcProcessEligRangeSoap,
            
            WebSvcProcessEligRangeSoap12,
        }
    }
}
