// ------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (c) CareSource, 2019. All rights reserved.
// 
//   WC.Services.OnBase
//   BaseResponse.cs
// </copyright>
// ------------------------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace

namespace WC.Services.ImportProcessor.Dotnet8.Models.v1.OnBase
{
	using System;
	using System.Text.Json.Serialization;

	public class BaseResponse<TResult>
	{
		[JsonConstructor]
		public BaseResponse(
			string title,
			int status,
			Guid correlationGuid,
			TResult result)
		{
			Title = title;
			Status = status;
			CorrelationGuid = correlationGuid;
			Result = result;
		}


		public BaseResponse(
			string title,
			int status,
			Guid correlationGuid)
			: this(
				title,
				status,
				correlationGuid,
				default(TResult))
		{ }

        /// <summary>
        ///    A short, human-readable summary of the problem type.It SHOULD NOT change from
        ///    occurrence to occurrence of the problem, except for purposes of
        ///    localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
        /// </summary>
        [JsonPropertyName("title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string Title { get; set; }

        /// <summary>
        ///    The HTTP status code([RFC7231], Section 6) generated by the origin server for this
        ///    occurrence of the problem.
        /// </summary>
        [JsonPropertyName("status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? Status { get; set; }

        /// <summary>
        ///    Gets or sets the Base Response{ T Model} Response Data
        /// </summary>
        [JsonPropertyName("result")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public TResult Result { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Trace Identifier
		/// </summary>
		[JsonPropertyName("correlationGuid")]
		public Guid CorrelationGuid { get; set; }
	}
}