// ------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (c) CareSource, 2021. All rights reserved.
// 
//   ImportProcessor
//   DocTypeNameResponse.cs
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace WC.Services.ImportProcessor.Dotnet8.Models.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text.Json.Serialization;
	public class DocTypeNameResponse : DocBaseResponse<DocumentType>
	{
		[JsonConstructor]
		public DocTypeNameResponse(
			string title,
			int status,
			Guid correlationGuid,
			DocumentType result)
			: base(
				title,
				status,
				correlationGuid,
				result)
		{ }

		public DocTypeNameResponse(
			string title,
			int status,
			Guid correlationGuid)
			: base(
				title,
				status,
				correlationGuid)
		{ }
	}

	public abstract class BaseModel
	{
		public long Id { get; set; }

		public string Name { get; set; }
	}

	public class DocumentType : BaseModel
	{
		public IEnumerable<KeywordModel> Keywords { get; set; }
	}

	public class DocBaseResponse<TResult>
	{
		[JsonConstructor]
		public DocBaseResponse(
			string title,
			int status,
			Guid correlationGuid,
			TResult result)
		{
			Title = title;
			Status = status;
			CorrelationGuid = correlationGuid;
			Result = result;
		}

		public DocBaseResponse(
			string title,
			int status,
			Guid correlationGuid)
			: this(
				title,
				status,
				correlationGuid,
				default)
		{ }

        /// <summary>
        ///    A short, human-readable summary of the problem type.It SHOULD NOT change from
        ///    occurrence to occurrence of the problem, except for purposes of
        ///    localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
        /// </summary>
        [JsonPropertyName("title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string Title { get; set; }

        /// <summary>
        ///    The HTTP status code([RFC7231], Section 6) generated by the origin server for this
        ///    occurrence of the problem.
        /// </summary>
        [JsonPropertyName("status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? Status { get; set; }

        /// <summary>
        ///    Gets or sets the Base Response{ T Model} Response Data
        /// </summary>
        [JsonPropertyName("result")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public TResult Result { get; set; }

		/// <summary>
		///    Gets or sets the Base Response{ T Model} Trace Identifier
		/// </summary>
		[JsonPropertyName("correlationGuid")]
		public Guid CorrelationGuid { get; set; }
	}
}