//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Services.Document.Dotnet8
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResouces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResouces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareSource.WC.Services.Document.StringResouces", typeof(StringResouces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Types.
        /// </summary>
        internal static string Document_Types {
            get {
                return ResourceManager.GetString("Document_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Document Types.
        /// </summary>
        internal static string Getting_Document_Types {
            get {
                return ResourceManager.GetString("Getting_Document_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Keyword Type.
        /// </summary>
        internal static string Getting_Keyword_Type {
            get {
                return ResourceManager.GetString("Getting_Keyword_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Keyword Types.
        /// </summary>
        internal static string Getting_Keyword_Types {
            get {
                return ResourceManager.GetString("Getting_Keyword_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword.
        /// </summary>
        internal static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
    }
}
